{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPKGA3WBOXioBPItK44Dex+",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/kusuma2718/FUTURE_ML_03/blob/main/resume_screening_system.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import re\n",
        "\n",
        "from sklearn.feature_extraction.text import TfidfVectorizer\n",
        "from sklearn.metrics.pairwise import cosine_similarity\n",
        "\n",
        "print(\"Resume Screening System Initialized\")\n",
        "\n",
        "# -------------------------------\n",
        "# STEP 1: CREATE RESUME DATA\n",
        "# -------------------------------\n",
        "resumes = {\n",
        "    \"candidate\": [\n",
        "        \"Candidate A\", \"Candidate B\", \"Candidate C\",\n",
        "        \"Candidate D\", \"Candidate E\"\n",
        "    ],\n",
        "    \"resume_text\": [\n",
        "        \"Python machine learning data analysis pandas numpy SQL\",\n",
        "        \"HTML CSS JavaScript React frontend UI UX\",\n",
        "        \"Java Spring Boot backend REST API microservices\",\n",
        "        \"Recruitment onboarding payroll HR compliance employee relations\",\n",
        "        \"Python statistics data visualization SQL Excel\"\n",
        "    ]\n",
        "}\n",
        "\n",
        "resume_df = pd.DataFrame(resumes);\n",
        "\n",
        "# -------------------------------\n",
        "# STEP 2: JOB DESCRIPTION\n",
        "# -------------------------------\n",
        "job_description = \"\"\"\n",
        "We are looking for a Data Scientist with strong skills in\n",
        "Python, Machine Learning, Data Analysis, SQL, Statistics,\n",
        "and Data Visualization.\n",
        "\"\"\"\n",
        "\n",
        "# -------------------------------\n",
        "# STEP 3: TEXT CLEANING FUNCTION\n",
        "# -------------------------------\n",
        "def clean_text(text):\n",
        "    text = text.lower()\n",
        "    text = re.sub(r\"[^a-z\\s]\", \"\", text)\n",
        "    text = re.sub(r\"\\s+\", \" \", text)\n",
        "    return text.strip()\n",
        "\n",
        "resume_df[\"clean_resume\"] = resume_df[\"resume_text\"].apply(clean_text)\n",
        "clean_job_desc = clean_text(job_description)\n",
        "\n",
        "print(\"Text cleaning completed\")\n",
        "\n",
        "# -------------------------------\n",
        "# STEP 4: REQUIRED SKILLS\n",
        "# -------------------------------\n",
        "required_skills = [\n",
        "    \"python\", \"machine learning\", \"data analysis\",\n",
        "    \"sql\", \"statistics\", \"data visualization\"\n",
        "]\n",
        "\n",
        "# -------------------------------\n",
        "# STEP 5: SKILL EXTRACTION\n",
        "# -------------------------------\n",
        "def extract_skills(text, skills):\n",
        "    return [skill for skill in skills if skill in text]\n",
        "\n",
        "resume_df[\"matched_skills\"] = resume_df[\"clean_resume\"].apply(\n",
        "    lambda x: extract_skills(x, required_skills)\n",
        ")\n",
        "\n",
        "# -------------------------------\n",
        "# ✅ FIX 2: DISPLAY RESULTS\n",
        "# -------------------------------\n",
        "print(\"\\n--- SKILL EXTRACTION RESULTS ---\\n\")\n",
        "display(resume_df[[\"candidate\", \"matched_skills\"]])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 302
        },
        "id": "2vJ4iIpuuztK",
        "outputId": "cae9182c-2ce2-4884-f0c7-aca469de5645"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Resume Screening System Initialized\n",
            "Text cleaning completed\n",
            "\n",
            "--- SKILL EXTRACTION RESULTS ---\n",
            "\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "     candidate                                  matched_skills\n",
              "0  Candidate A  [python, machine learning, data analysis, sql]\n",
              "1  Candidate B                                              []\n",
              "2  Candidate C                                              []\n",
              "3  Candidate D                                              []\n",
              "4  Candidate E   [python, sql, statistics, data visualization]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-19a7df15-3540-4151-8e49-f147db5e8f4e\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>candidate</th>\n",
              "      <th>matched_skills</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Candidate A</td>\n",
              "      <td>[python, machine learning, data analysis, sql]</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Candidate B</td>\n",
              "      <td>[]</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Candidate C</td>\n",
              "      <td>[]</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Candidate D</td>\n",
              "      <td>[]</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Candidate E</td>\n",
              "      <td>[python, sql, statistics, data visualization]</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-19a7df15-3540-4151-8e49-f147db5e8f4e')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-19a7df15-3540-4151-8e49-f147db5e8f4e button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-19a7df15-3540-4151-8e49-f147db5e8f4e');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "summary": "{\n  \"name\": \"display(resume_df[[\\\"candidate\\\", \\\"matched_skills\\\"]])\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"candidate\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"Candidate B\",\n          \"Candidate E\",\n          \"Candidate C\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"matched_skills\",\n      \"properties\": {\n        \"dtype\": \"object\",\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ]
    }
  ]
}